ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER MOS IDENTIFIED BY bitc5600;

GRANT CREATE SESSION TO MOS;

GRANT CREATE TABLESPACE TO MOS;

GRANT CREATE TABLE TO MOS;

GRANT DELETE, SELECT, UPDATE , INSERT ON MOS.PLAYER TO MOS;

ALTER USER MOS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;