SELECT HIREDATE FROM EMP WHERE  HIREDATE = '80/12/17';

ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';

SELECT * FROM EMP;

SELECT * FROM EMP WHERE SAL BETWEEN 1500 AND 2000;

SELECT * FROM EMP WHERE JOB LIKE 'S%';

SELECT * FROM EMP WHERE JOB LIKE 'S_______';

SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE COMM IS NOT NULL;

-- 사원들 중에 보너스가 500보다 작은사람!!

SELECT * FROM EMP WHERE COMM <500;

SELECT NVL(NULL,0) , NVL(100,3) FROM DUAL;
                                                                                                                                                  
SELECT ENAME , SAL ,NVL(COMM,0) FROM EMP WHERE NVL(COMM,0)<500;

SELECT * FROM EMP WHERE SAL>1000 ORDER BY SAL DESC;

SELECT POWER(2,10) FROM DUAL;

SELECT MOD(123,10) FROM DUAL;

SELECT CEIL(123.45) FROM DUAL;

SELECT SYSDATE FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD-HH-MI-SS';

SELECT DECODE('LOVE','LEVE','TRUE') FROM DUAL;

SELECT * FROM PROFESSOR;

SELECT DEPTNO,NAME,DEPTNO,DECODE(DEPTNO , 101,'COMPUTER ENGNEERING','ETC') FROM PROFESSOR ; 

SELECT DEPTNO , NAME , DECODE(DEPTNO,101,'COMPUTER ENGNEERING',102,'MULTIMEDIA ENGINEERING',103,'SOFTWARE ENGINEERING','ETC') "DNAME" FROM PROFESSOR;

SELECT DEPTNO , NAME , DECODE(DEPTNO,101,DECODE(NAME,'조인형','BEST!')) "ETC" FROM PROFESSOR;

SELECT DEPTNO , NAME , DECODE(DEPTNO,'101',DECODE(NAME,'조인형','BEST!','GOOD!')) "ETC" FROM PROFESSOR;

SELECT DEPTNO , NAME , DECODE(DEPTNO,'101',DECODE(NAME,'조인형','BEST!','GOOD!'),'N/A') "ETC" FROM PROFESSOR;

SELECT * FROM STUDENT;
SELECT NAME , JUMIN , DECODE(SUBSTR(JUMIN,7,1),1,'MAN',2,'WOMAN') "GENGER" FROM STUDENT WHERE DEPTNO1 = 101;

SELECT NAME , TEL , DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'02','SEOUL','031','GYEONGGI','051','BUSAN','052','ULSAN','055','GYEONGNAM') "LOC" FROM STUDENT WHERE DEPTNO1 = '101';

SELECT * FROM EMP WHERE EMPNO NOT IN (BETWEEN  7654 AND 7782);

SELECT COUNT(ENAME) FROM EMP;

SELECT MAX(SAL) FROM EMP;

SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

SELECT MAX(SAL),JOB FROM EMP GROUP BY JOB ;

SELECT SUM(SAL) , DEPTNO FROM EMP GROUP BY DEPTNO ORDER BY 1;

SELECT JOB, COUNT(*) FROM EMP GROUP BY JOB;

SELECT JOB, TRUNC(AVG(SAL)) FROM EMP GROUP BY JOB HAVING JOB<>'MANAGER';

SELECT DEPTNO"부서번호" , FLOOR(AVG(SAL))"평균 급여" FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)>=2000;

SELECT * FROM GOGAK;

--3~8 최고값 9~나머지 최고값

SELECT MAX(POINT) FROM GOGAK;

SELECT MAX(POINT) FROM GOGAK WHERE ROWNUM > 0 AND ROWNUM <9
UNION ALL
SELECT MAX(POINT) FROM (SELECT MAX(POINT) , ROWNUM "NO" FROM GOGAK) WHERE NO>8 AND NO<21;

SELECT GNO,GNAME, POINT , NO , DECODE(NO,1,1,2,1,3,1,4,1,5,1,6,1,7,1,8,1,2) FROM(SELECT GNO, GNAME , POINT , ROWNUM "NO" FROM GOGAK);
---------------------------------------------------
SELECT MAX(POINT)
FROM 
(
    SELECT GNO,GNAME, POINT , NO , 
    CASE WHEN NO <9 THEN 1 ELSE 2 END "G"
    FROM
    (
        SELECT GNO, GNAME , POINT , ROWNUM "NO" 
        FROM GOGAK
    ) 
)
GROUP BY G;
-------------------------------------------------
SELECT GNO, GNAME , POINT , ROWNUM "NO" 
        FROM GOGAK;
-------------------------------------------------
SELECT GNO,GNAME, POINT , NO , 
    CASE WHEN NO <9 THEN 1 ELSE 2 END "G"
    FROM
    (
        SELECT GNO, GNAME , POINT , ROWNUM "NO" 
        FROM GOGAK
    ) ;







